# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build use-context/host module
      working-directory: use-context/host
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build use-context/nav module
      working-directory: use-context/nav
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build use-context/store module
      working-directory: use-context/store
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build redux/host module
      working-directory: redux/host
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build redux/nav module
      working-directory: redux/nav
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Build redux/store module
      working-directory: redux/store
      run: |
        npm install
        npm run build
      env:
        CI: true